### ISSUE TITLE
Test https://beta.oerworldmap.org by @j0hj0h

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#191]
# [Landing Page](https://beta.oerworldmap.org)
- [x] I can click on all links

# [User registration](https://beta.oerworldmap.org/user/register)
- [x] I can register a user
- [ ] I receive the verification email and can click the link
- [x] I can log in with the new user
- [x] I can log back out
- [ ] I can reset the password by entering the email
- [ ] I can log in with the new password sent by email
- [ ] I can change the new password to an own one
- [ ] I can log in with the new password I supplied
- [ ] I can administer groups (requires admin privileges)

# [Map / List](https://beta.oerworldmap.org/resource/)
- [x] I can move around on the map
- [x] I can click on large clusters of pins to zoom in
- [x] I can click on small clusters of pins to get a list popup
- [x] I can click on individual pins
- [x] I can show the list by clicking on the list icon in the search box
- [ ] I can set and unset filters
- [x] I can show and hide the extended filter section
- [x] I can share, export and print the list
- [ ] I can add one entry of each type
- [ ] I can show the global statistics
- [ ] I can list the recent additions
- [ ] I can list the likes
- [ ] I can list the lighthouses

# [Individual items](https://beta.oerworldmap.org/resource/urn%3Auuid%3A29056e88-727b-407e-b00a-16df279ac506)
- [ ] I can find the data I expect
- [ ] I can like and unlike the item
- [ ] I can add a lighthouse
- [ ] I can set the `I'm a member` relation for organizations
- [ ] I can set the `I'm attending` relation for events
- [ ] I can add a comment
- [ ] I can edit and save the entry
- [ ] I can view the log of the entry (requires admin privileges)
- [ ] I can delete comments (requires admin privileges)
- [ ] I can delete lighthouses (requires admin privileges)

**Comment by j0hj0h** [comment]
- On https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Event I see all events, but it says "20 of of 276 results"
- In the `user/register` modal it's not so obvious that the first two checkboxes are required, the others not. For the NL it's clear from the wording, but to publish your email address seems mandatory, if you don't spot the star at the first two. I suggest to have "(Required)" and "(Optional)" behind the texts
- After registration, when I see the notification "Successfully registered user ..." clicking on Login, doesn't open the `user/register` modal any longer, probably because I'm on that URL already
- In Safari 11.0.3: Clicking on a type filter or on the "Apply Filter" button in the dropdown filters throws JS error `TypeError: r.entries is not a function. (In 'r.entries()', 'r.entries' is undefined)` ... nothing happens
- In Safari 11.0.3: Hitting enter in the search box has no effect
- Maybe the magnifier icon should trigger the search as well

**Comment by literarymachine** [comment]
> On https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Event I see all events, but it says "20 of of 276 results"

See #224

> In the user/register modal it's not so obvious that the first two checkboxes are required, the others not. For the NL it's clear from the wording, but to publish your email address seems mandatory, if you don't spot the star at the first two. I suggest to have "(Required)" and "(Optional)" behind the texts

Having an asterisks to indicate is a very common pattern to indicate required fields, I would argue the usage of `(Required)` and `(Optional)` is not. We'll style the asterisks more prominent: #228.

> After registration, when I see the notification "Successfully registered user ..." clicking on Login, doesn't open the user/register modal any longer, probably because I'm on that URL already

Exactly, it is because you are on that URL already. Since you have to click on the verification link anyways, it is not a big issue. But we'll style the `Successfully registered user ...` notification as a modal so that the `Login` link will be unavailable anyways: #225.

> In Safari 11.0.3: Clicking on a type filter or on the "Apply Filter" button in the dropdown filters throws JS error TypeError: r.entries is not a function. (In 'r.entries()', 'r.entries' is undefined) ... nothing happens
> In Safari 11.0.3: Hitting enter in the search box has no effect

See #226.

> Maybe the magnifier icon should trigger the search as well

See ##227.
