### ISSUE TITLE
Re-configure Crowdin

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#210]
- UI-i18n now resides at ~https://github.com/hbz/oerworldmap-ui/tree/master/src/locale~ https://github.com/hbz/oerworldmap-ui/tree/master/docs/_data/locale
- Static pages are at ~https://github.com/hbz/oerworldmap-static~ https://github.com/hbz/oerworldmap-ui/tree/master/docs, ~but we are thinking about also moving that content innto oerworldmap-ui.~
- Changes in the i18n files need to be synced

**Comment by acka47** [comment]
Considering our past experiences with the CrowdIn Github integration (especially CrowdIn not being able to automatically pull existing translations from GitHub) and having looked at other options, here is my suggestion for the process:

1. Delete all files from https://crowdin.com/project/oerworldmap/settings#files.
2. update GitHub integration to the new repo (oerworldmap-ui) only pointing to the source files (en) without indicating any language for translation (so that CrowdIn does not create empty translation files that overwrite the existing translations).
3. Upload existing translations (https://support.crowdin.com/uploading-translations/, CrowdIn claims that it "automatically matches uploaded translations with appropriate source files and languages.")
4. The resulting i18n branch from CrowdIn should be identical with the current master on GitHub.
5. Done

What do you think?

**Comment by literarymachine** [comment]
> The resulting i18n branch from CrowdIn should be identical with the current master on GitHub.

We have a couple of changes in the `ui.properties` (`en`) version, but I think this should not be a problem.

> What do you think?

Sounds like a plan! I assume it won't be a problem to add the static pages later?

**Comment by acka47** [comment]
> I assume it won't be a problem to add the static pages later?

It shouldn't

**Comment by acka47** [comment]
We should keep in mind that until the static pages are also moved to oerworldmap-ui it won't be possible to translate them via CrowdIn...

**Comment by acka47** [comment]
As @literarymachine suggested on the phone I will try this out with a fork of oerworldmap-ui first.

**Comment by acka47** [comment]
It looks like I forgot one thing with the approach from https://github.com/hbz/oerworldmap-ui/issues/210#issuecomment-379191799. I can not upload translated markdown files but CrowdIn needs XLIFF translation files. That would not be a big problem if I had exported the translations before deleting them, but I didn't. :cry:  I am afraid we have to redo the translation of the static pages in Crowdin. I am very sorry, especially as I vaguely remember that this happened before.

**Comment by acka47** [comment]
I did a long clickthrough through CrowdIn and the static page translations are alos in there now for German and Portuguese...

**Comment by acka47** [comment]
Closing.

**Comment by literarymachine** [comment]
Landing page not configured yet, will reopen when necessary.
